services:
  postgres:
    image: postgres:17.4
    env_file:
      - env/.env
    ports:
      - "5432:5432"
    volumes:
      - ./.tmp/volumes/pg:/var/lib/postgresql/data

  api:
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./src:/app/src
    env_file:
      - env/.env

  pgadmin:
    image: dpage/pgadmin4:9.8
    env_file:
      - env/.env
    user: root
    ports:
      - "5050:80"
    volumes:
      - ./.pgadmin/volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  localstack:
    container_name: hirable.localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - SERVICES=sqs,s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack_data:
    driver: local
